routes/web.php
<?php

use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\TestingContoller;
use App\Http\Controllers\TestingController;
use App\Models\Item;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



//retrieve page or data
Route::get('/home', [HomeController::class, 'index'])->middleware('auth')->name('home');

// Route::get('testing_function',function(){
//     //process
//     echo "Hello World";
// });


Route::name('modul.')->prefix('modul')->middleware(['auth'])->group(function(){
    Route::get('function_success',[HomeController::class, 'papar'])->name('function_success');

    //papar static age
    Route::view('papar_static_page','welcome')->name('papar_static_page');

    Route::get('registration',[HomeController::class, 'register'])->middleware('CheckingAge')->name('registration');

    Route::get('validation-form',[TestingController::class, 'form'])->name('validation-form');

    Route::post('validation-store',[TestingController::class, 'store'])->name('validation-store');

    Route::name('item.')->prefix('item')->group(function(){
        Route::get('index',[ItemController::class,'index'])->name('index');
        Route::get('create',[ItemController::class,'create'])->name('create');
        Route::post('store',[ItemController::class,'store'])->name('store');
        Route::get('fetch_data',[ItemController::class,'fetch_data'])->name('fetch_data');
        Route::get('{id}/edit',[ItemController::class,'edit'])->name('edit');
        Route::post('{id}/update',[ItemController::class,'update'])->name('update');
        Route::post('{id}/destroy}',[ItemController::class,'destroy'])->name('destroy');
    });
});

Route::get('testing-query',function(){
    /*------Retrieve all data----*/
    $query1 = Item::all();

    $query2 = Item::findOrFail(1);

    /*------Retrieve one data where item_name like lap----*/
    $query3 = Item::where('item_name','like','%lap%')->first();

    /*------Retrieve all data----*/
    $query4 = Item::get();

    /*------Checking existen of senduk in item table----*/
    $query5 = Item::where('item_name','senduk')->exists();

    /*------get sum price of items----*/
    $query6 = Item::where('user_id','=',1)->sum('price');

    /*------Retrieve one data where item_name like lap and user_id = 1 ----*/
    $query7 = Item::where('item_name','like','%lap%')->where('user_id','=',1)->first();

    /*------Retrieve one data where item_name like lap or user_id = 1 ----*/
    $query8 = Item::where('item_name','like','%lap%')->orWhere('user_id','=',1)->first();

    /*------Retrieve number of row found where user_id = 1 ----*/
    $query9 = Item::where('user_id','=',1)->count();

    /*------get average price of items where user_id = 1----*/
    $query10 = Item::where('user_id','=',1)->avg('price');

    /*------get data where condition from other table in relationship----*/
    $request_name = 'daus';

    $query11 = Item::whereHas('user',function($q) use ($request_name){
        $q->where('name','like','%'. $request_name.'%');
    })->get();

    /*------get user id=2 who has items----*/
    $query12 = User::whereHas('item')->get();

     /*------get data where condition from other table in relationship if $request not empty----*/
    $request = 'Handphone';

    $query13 = Item::when(($request != null or $request != ''),function($query)use ($request){
        $query->where(function($query) use ($request){
            $query->whereHas('user',function($q) use ($request){
                $q->where('name','like','%'. $request.'%');
            });
            $query->orWhere('item_name','like','%'. $request.'%');
        });
    })
    ->get();

    /*------how to use raw query----------*/
    $value = 'aus';
    $query14 = User::whereRaw(' lower(name) like :value', ['value' => '%'.strtolower($value).'%'])->first();

    $query14 = User::whereRaw(' lower(name) like ?', ['%'.strtolower($value).'%'])->first();

    // dd($query1,$query2,$query3,$query5,$query6,$query7, $query8, $query9, $query10);

    /*------Query builder join table-----------*/
    $query15 = DB::table('users as u')
                ->select('u.id as user_id','t.id as tag_id','i.id as item_id','u.name','tag_name','item_name')
                ->join('items as i','i.user_id','=','u.id')
                ->join('tags as t','i.tag_id','=','t.id')
                ->where('t.id','=',1)
                ->get();

    dd($query15);
});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $table = 'items';

    //  protected $primaryKey = 'uuid';

    public function user()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function tag()
    {
        return $this->belongsTo(Tag::class,'tag_id','id');
    }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ItemRequest;
use App\Http\Requests\ItemRequestUpdate;
use App\Models\Item;
use App\Models\Tag;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;

class ItemController extends Controller
{
    // public function index()
    // {

    //     if(!request()->filled('size')){
    //         $size = 2;
    //     }else{
    //         $size = request()->size;
    //     }

    //     //select * from users where ((name  = "firdaus" or age = 30) or race= malay)

    //     $search = request()->search;

        //     $data = Item::with(['user','tag'])
        //             ->when(request()->filled('search'),function($q) use ($search){

        //                 $q->where(function($q) use ($search){ //grouping function
        //                     $q->where('item_name','like','%'.$search.'%');

        //                     $q->orWhere('description','like','%'.$search.'%');

        //                     $q->orWhereHas('user',function($query) use ($search){
        //                         $query->where('name',$search);
        //                     });

        //                     $q->orWhereHas('tag',function($query) use ($search){
        //                         $query->where('tag_name',$search);
        //                     });
        //                 });

    //             })->paginate($size);

    //     return view('item.index',compact('data'));
    // }

    public function index()
    {

        $data = Item::with(['user','tag'])->orderBy('created_at','DESC')->paginate(5);

        return view('item.index-2',compact('data'));
    }

    function fetch_data(Request $request)
    {
     if($request->ajax())
     {
        $sort_by = $request->get('sortby');
        $sort_type = $request->get('sorttype');
        $search = $request->get('query');
        $search = str_replace(" ", "%", $search);
        $entry = (request()->filled('entry')) ? request()->get('entry') : 2 ;

        $data = Item::with(['user','tag'])
        ->when(request()->filled('query'),function($q) use ($search){

            $q->where(function($q) use ($search){ //grouping function
                $q->where('item_name','like','%'.$search.'%');

                $q->orWhere('description','like','%'.$search.'%');

                $q->orWhereHas('user',function($query) use ($search){
                    $query->where('name',$search);
                });

                $q->orWhereHas('tag',function($query) use ($search){
                    $query->where('tag_name',$search);
                });
            });

        })
        ->orderBy($sort_by, $sort_type)
        ->paginate($entry);
        return view('item.pagination-data', compact('data'))->render();
        }
    }

    public function create()
    {
        $tags = Tag::get();
        $item = new Item();
        return view('item.create',compact('tags','item'));
    }

    public function store(ItemRequest $request)
    {
        $item = new Item();
        $item->user_id = Auth::user()->id;
        $item->tag_id = $request->tag;
        $item->item_name = $request->item_name;
        $item->price = $request->price;
        $item->description = $request->description;
        $item->save();

        // Session::flash('status', 'berjaya');

        return redirect()->route('modul.item.index')->with('success','Item successfully registered');
    }

    public function edit($id)
    {
        $id = decrypt_string($id);

        $item = Item::findOrFail($id);
        $tags = Tag::get();
        return view('item.edit',compact('item','tags'));
    }

    public function update(ItemRequestUpdate $request,$id)
    {
        $id = decrypt_string($id);

        $item = Item::findOrFail($id);
        $item->tag_id = $request->tag;
        $item->item_name = $request->item_name;
        $item->price = $request->price;
        $item->description = $request->description;
        $item->save();

        return redirect()->route('modul.item.index')->with('success','Item successfully updated');
    }

    public function destroy($id)
    {
        $id = decrypt_string($id);

        $item = Item::findOrFail($id);
        $item->delete();

        return redirect()->route('modul.item.index')->with('success','Item successfully deleted');
    }
}

resources/views/item/create.blade.php
@extends('layouts.template-1.app')

@section('title','Add New Item')

@section('content')
    <form action="{{route('modul.item.store')}}" method="post">
        @csrf
        @include('item.form',['button'=>'save'])
    </form>
@endsection

resources/views/item/edit.blade.php
@extends('layouts.template-1.app')

@section('title','Edit Item')

@section('content')
    <form action="{{route('modul.item.update',encrypt_string($item->id))}}" method="post">
        @csrf
        @include('item.form',['button'=>'update'])
    </form>
@endsection

resources/views/item/form.blade.php
<div class="form-group">
    <label for="exampleInputEmail1">Item Name:</label>
    <input type="text" name="item_name" autocomplete="off" value="{{ old('item_name',$item->item_name)}}" class="form-control @error('item_name') is-invalid" @enderror  placeholder="Enter item name"  aria-invalid="true">
    @error('item_name')
        <span class="error invalid-feedback">{{$message}}</span>
    @enderror
</div>
<div class="form-group">
    <label>Item Price:</label>
    <input type="text" name="price" value="{{ old('price',$item->price)}}" autocomplete="off"  class="form-control @error('price') is-invalid" @enderror  placeholder="Enter item price"  aria-invalid="true">
    @error('price')
        <span class="error invalid-feedback">{{$message}}</span>
    @enderror
</div>

<div class="form-group">
    <label>Item Description:</label>
    <textarea type="text" name="description"   class="form-control @error('description') is-invalid @enderror ">{{old('description',$item->description)}}</textarea>
    @error('description')
        <span class="error invalid-feedback">{{$message}}</span>
    @enderror
</div>

<div class="form-group">
    <label>Tag:</label>
    <select name="tag" class="form-control">
        <option >Select</option>
        @foreach ($tags as $tag)
            <option value="{{ $tag->id }}" @if(old('tag',$item->tag_id) == $tag->id) selected @endif>{{$tag->tag_name}}</option>
        @endforeach
    </select>
    @error('tag')
        <span class="error invalid-feedback">{{$message}}</span>
    @enderror
</div>

<button type="submit" class="btn btn-primary">{{$button}}</button>

resources/views/item/index-2.blade.php
@extends('layouts.template-1.app')

@section('title','List of item')

@section('content')

<a href="{{ route('modul.item.create')}}" class="btn btn-primary float-right">Add Item</a>
<div class="row mb-2">
    <div class="col-md-2">
        <select class="form-control" id="entry">
            <option value ="5">5</option>
            <option value ="10">10</option>
            <option value ="15">15</option>
        </select>
    </div>
    <div class="col-md-10">
        <input type="text" placeholder="Search" id="search" class="form-control">
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th class="sorting" data-sorting_type="asc" data-column_name="item_name" style="cursor: pointer">Item Name<span id="item_name_icon"></span></th>
                <th>Tag</th>
                <th class="sorting" data-sorting_type="asc" data-column_name="price" style="cursor: pointer">Price <span id="price_icon"></span></th>
                <th>Description</th>
                <th>Owner</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="item-data">
           @include('item.pagination-data')
        </tbody>
    </table>
    <input type="hidden" name="hidden_page" id="hidden_page" value="1" />
    <input type="hidden" name="hidden_column_name" id="hidden_column_name" value="item_name" />
    <input type="hidden" name="hidden_sort_type" id="hidden_sort_type" value="asc" />

</div>
@endsection
@push('js')
    <script>
        $(document).ready(function(){



            $( ".confirmation" ).click(function() {
                var id = $(this).data('id');
                var title = $(this).data('title');
                Swal.fire({
                    title: 'Confirmation',
                    html: "Are you sure you want to remove <b>"+title.toUpperCase()+"</b>? You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#6259ca',
                    cancelButtonColor: '#f16d75',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.value) {
                        $(id).submit();
                    }
                });
            })


            function clear_icon()
            {
                $('#item_name_icon').html('');
                $('#price_icon').html('');
            }


            function fetch_data(page, sort_type, sort_by, query, entry)
            {
                $.ajax({
                    url:"/modul/item/fetch_data?page="+page+"&sortby="+sort_by+"&sorttype="+sort_type+"&query="+query+"&entry="+entry,
                    success:function(data)
                    {
                        $('#item-data').html('');
                        $('#item-data').html(data);
                    }
                })
            }

            $(document).on('keyup', '#search', function(){
                var query = $('#search').val();
                var column_name = $('#hidden_column_name').val();
                var sort_type = $('#hidden_sort_type').val();
                var page = $('#hidden_page').val();
                var entry = $('#entry').val();
                fetch_data(page, sort_type, column_name, query, entry);
            });

            $(document).on('change', '#entry', function () {
                var query = $('#search').val();
                var column_name = $('#hidden_column_name').val();
                var sort_type = $('#hidden_sort_type').val();
                var page = 1;
                var entry = $('#entry').val();
                fetch_data(page, sort_type, column_name, query, entry);
            });

            $(document).on('click', '.sorting', function(){
                var column_name = $(this).data('column_name');
                var order_type = $(this).data('sorting_type');
                var reverse_order = '';
                if(order_type == 'asc')
                {
                    $(this).data('sorting_type', 'desc');
                    reverse_order = 'desc';
                    clear_icon();
                    $('#'+column_name+'_icon').html('<i class="fa fa-sort-asc"></i>');
                }

                if(order_type == 'desc')
                {
                    $(this).data('sorting_type', 'asc');
                    reverse_order = 'asc';
                    clear_icon
                    $('#'+column_name+'_icon').html('<i class="fa fa-sort-desc"></i>');
                }

                $('#hidden_column_name').val(column_name);
                $('#hidden_sort_type').val(reverse_order);

                var page = $('#hidden_page').val();
                var query = $('#search').val();
                var entry = $('#entry').val();

                fetch_data(page, reverse_order, column_name, query, entry);

            });

            $(document).on('click', '.pagination a', function(event){
                event.preventDefault();

                var page = $(this).attr('href').split('page=')[1];
                $('#hidden_page').val(page);

                var column_name = $('#hidden_column_name').val();
                var sort_type = $('#hidden_sort_type').val();
                var query = $('#search').val();
                var entry = $('#entry').val();

                $('li').removeClass('active');
                $(this).parent().addClass('active');

                fetch_data(page, sort_type, column_name, query, entry);
            });


        });
    </script>
@endpush

resources/views/item/index.blade.php
@extends('layouts.template-1.app')

@section('title','List of item')

@section('content')
<div class="row mb-2">
    <div class="col-md-2">
        <select class="form-control" id="size" onchange="table_size(this.value)">
            <option @if(request()->size == 2) selected @endif value ="2">2</option>
            <option @if(request()->size == 10) selected @endif value ="10">10</option>
            <option @if(request()->size == 15) selected @endif value ="15">15</option>
        </select>
    </div>
    <div class="col-md-10">
        <input type="text" placeholder="Search" id="search" value="{{request()->search}}" class="form-control" onkeydown="search(this.value)">
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Item Name</th>
                <th>Tag</th>
                <th>Price</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $key => $item)
                <tr>
                    <td>{{$data->firstItem() + $key}}</td>
                    <td>{{$item->item_name}}</td>
                    <td>{{$item->tag->tag_name}}</td>
                    <td>{{number_format($item->price,2)}}</td>
                    <td>{!! $item->description !!}</td>
                    <td>{{$item->user->name}}</td>
                    <td>
                        <a href="" class="btn btn-info"><i class="fas fa-edit"></i></a>
                        <a href="" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7">No record</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{ $data->appends(['size'=> request()->size, 'search' => request()->search])->links('vendor.pagination.bootstrap-4')}}
</div>
@endsection
@push('js')
    <script>
        function table_size(size)
        {
            var search = $("#search").val();
            window.location.replace("/modul/item/index?search="+ search +"&size=" + size);
        }

        function search(search)
        {
            var size = $("#size").val();
            if(event.key === 'Enter') {
                window.location.replace("/modul/item/index?search=" + search + "&size=" + size);
            }
        }
    </script>
@endpush

resources/views/item/pagination-data.blade.php
@forelse($data as $key => $item)
<tr>
    <td>{{$data->firstItem() + $key}}</td>
    <td>{{$item->item_name}}</td>
    <td>{{$item->tag->tag_name}}</td>
    <td>{{number_format($item->price,2)}}</td>
    <td>{!! $item->description !!}</td>
    <td>{{$item->user->name}}</td>
    <td>
        <a href="{{ route('modul.item.edit', encrypt_string($item->id))}}" class="btn btn-info"><i class="fas fa-edit"></i></a>
        {{-- <a href="javascript:void(0)" class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('delete-data-{{$item->id}}').submit();"><i class="fas fa-trash"></i></a> --}}
        <a href="javascript:void(0)" class="btn btn-danger confirmation" data-id="#delete-data-{{$item->id}}" data-title="{{$item->item_name}}"><i class="fas fa-trash"></i></a>
        <form id="delete-data-{{$item->id}}" action="{{ route('modul.item.destroy',encrypt_string($item->id)) }}" method="POST" class="d-none">
            @csrf
        </form>
    </td>
</tr>

@empty
    <tr>
        <td colspan="7">No record</td>
    </tr>
@endforelse
<tr class="border-bottom">
    <td colspan="7">
        {!!  $data->links('vendor.pagination.bootstrap-4') !!}
    </td>
</tr>