routes/web.php
<?php

use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\TestingContoller;
use App\Http\Controllers\TestingController;
use App\Models\Item;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



//retrieve page or data
Route::get('/home', [HomeController::class, 'index'])->middleware('auth')->name('home');

// Route::get('testing_function',function(){
//     //process
//     echo "Hello World";
// });


Route::name('modul.')->prefix('modul')->middleware(['auth'])->group(function(){
    Route::get('function_success',[HomeController::class, 'papar'])->name('function_success');

    //papar static age
    Route::view('papar_static_page','welcome')->name('papar_static_page');

    Route::get('registration',[HomeController::class, 'register'])->middleware('CheckingAge')->name('registration');

    Route::get('validation-form',[TestingController::class, 'form'])->name('validation-form');

    Route::post('validation-store',[TestingController::class, 'store'])->name('validation-store');

    Route::name('item.')->prefix('item')->group(function(){
        Route::get('index',[ItemController::class,'index'])->name('index');
        Route::get('create',[ItemController::class,'create'])->name('create');
        Route::post('store',[ItemController::class,'store'])->name('store');
        Route::get('fetch_data',[ItemController::class,'fetch_data'])->name('fetch_data');
        Route::get('{id}/edit',[ItemController::class,'edit'])->name('edit');
        Route::post('{id}/update',[ItemController::class,'update'])->name('update');
        Route::post('{id}/destroy}',[ItemController::class,'destroy'])->name('destroy');
    });
});

Route::get('testing-query',function(){
    /*------Retrieve all data----*/
    $query1 = Item::all();

    $query2 = Item::findOrFail(1);

    /*------Retrieve one data where item_name like lap----*/
    $query3 = Item::where('item_name','like','%lap%')->first();

    /*------Retrieve all data----*/
    $query4 = Item::get();

    /*------Checking existen of senduk in item table----*/
    $query5 = Item::where('item_name','senduk')->exists();

    /*------get sum price of items----*/
    $query6 = Item::where('user_id','=',1)->sum('price');

    /*------Retrieve one data where item_name like lap and user_id = 1 ----*/
    $query7 = Item::where('item_name','like','%lap%')->where('user_id','=',1)->first();

    /*------Retrieve one data where item_name like lap or user_id = 1 ----*/
    $query8 = Item::where('item_name','like','%lap%')->orWhere('user_id','=',1)->first();

    /*------Retrieve number of row found where user_id = 1 ----*/
    $query9 = Item::where('user_id','=',1)->count();

    /*------get average price of items where user_id = 1----*/
    $query10 = Item::where('user_id','=',1)->avg('price');

    /*------get data where condition from other table in relationship----*/
    $request_name = 'daus';

    $query11 = Item::whereHas('user',function($q) use ($request_name){
        $q->where('name','like','%'. $request_name.'%');
    })->get();

    /*------get user id=2 who has items----*/
    $query12 = User::whereHas('item')->get();

     /*------get data where condition from other table in relationship if $request not empty----*/
    $request = 'Handphone';

    $query13 = Item::when(($request != null or $request != ''),function($query)use ($request){
        $query->where(function($query) use ($request){
            $query->whereHas('user',function($q) use ($request){
                $q->where('name','like','%'. $request.'%');
            });
            $query->orWhere('item_name','like','%'. $request.'%');
        });
    })
    ->get();

    /*------how to use raw query----------*/
    $value = 'aus';
    $query14 = User::whereRaw(' lower(name) like :value', ['value' => '%'.strtolower($value).'%'])->first();

    $query14 = User::whereRaw(' lower(name) like ?', ['%'.strtolower($value).'%'])->first();

    // dd($query1,$query2,$query3,$query5,$query6,$query7, $query8, $query9, $query10);

    /*------Query builder join table-----------*/
    $query15 = DB::table('users as u')
                ->select('u.id as user_id','t.id as tag_id','i.id as item_id','u.name','tag_name','item_name')
                ->join('items as i','i.user_id','=','u.id')
                ->join('tags as t','i.tag_id','=','t.id')
                ->where('t.id','=',1)
                ->get();

    dd($query15);
});

resources/views/layouts/template-1/app.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@yield('title','Laravel Training')</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ asset('AdminLTE-master/plugins/fontawesome-free/css/all.min.css' ) }}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('AdminLTE-master/dist/css/adminlte.min.css' ) }}">

  <link href="{{ asset('AdminLTE-master/sweetalert2/dist/sweetalert2.min.css') }}" rel="stylesheet">

    @stack('css')
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
@include('layouts.template-1.top-navigation')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ asset('AdminLTE-master/dist/img/AdminLTELogo.png' ) }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('AdminLTE-master/dist/img/user2-160x160.jpg' ) }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name}} {{-- auth()->user()->name --}}</a>
          <a  href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      @include('layouts.template-1.menu')
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mt-2">
                @include('layouts.template-1.feedback')
            </div>
            <!-- /.col-md-6 -->
            <div class="col-lg-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h5 class="m-0">@yield('title')</h5>
                    </div>
                    <div class="card-body">
                        @yield('content')
                    </div>
                </div>
            </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
@include('layouts.template-1.footer')
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('AdminLTE-master/plugins/jquery/jquery.min.js' ) }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('AdminLTE-master/plugins/bootstrap/js/bootstrap.bundle.min.js' ) }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('AdminLTE-master/dist/js/adminlte.min.js' ) }}"></script>
<!-- Internal Sweet-Alert js-->
<script src="{{ asset('AdminLTE-master/sweetalert2/dist/sweetalert2.min.js') }}"></script>

@stack('js')
</body>
</html>

resources/views/layouts/template-1/feedback.blade.php
@if(session('success'))
    <div class="alert alert-success">
       {{session('success')}}
    </div>
@endif

@if(session('warning'))
    <div class="alert alert-warning">
        {{session('warning')}}
    </div>
@endif

@if(session('info'))
    <div class="alert alert-info">
        {{session('info')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

resources/views/layouts/template-1/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

resources/views/layouts/template-1/menu.blade.php
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
      <li class="nav-item menu-open">
        <a href="#" class="nav-link">
          <i class="nav-icon fas fa-tachometer-alt"></i>
          <p>
            Modul Item
            <i class="right fas fa-angle-left"></i>
          </p>
        </a>
        <ul class="nav nav-treeview">
          <li class="nav-item">
            <a href="{{route('modul.item.index')}}" class="nav-link">
              <i class="far fa-circle nav-icon"></i>
              <p>Item List</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="far fa-circle nav-icon"></i>
              <p>Inactive Page</p>
            </a>
          </li>
        </ul>
      </li>
      {{-- <li class="nav-item">
        <a href="{{ route('home')}}" class="nav-link">
          <i class="nav-icon fas fa-th"></i>
          <p>
            Testing Route
          </p>
        </a>
      </li> --}}
      <li class="nav-item">
        <a href="{{ url('/home')}}" class="nav-link">
          <i class="nav-icon fas fa-th"></i>
          <p>
            Testing Route
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route('modul.papar_static_page')}}" class="nav-link">
          <i class="nav-icon fas fa-desktop"></i>
          <p>
            Papar Static Page
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route('modul.registration')}}" class="nav-link">
          <i class="nav-icon fas fa-user"></i>
          <p>
            Testing Middleware
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route('modul.validation-form')}}" class="nav-link">
          <i class="nav-icon fas fa-user"></i>
          <p>
           Validation Form
          </p>
        </a>
      </li>


    </ul>
  </nav>

resources/views/layouts/template-1/top-navigation.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE-master/dist/img/user1-128x128.jpg' ) }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE-master/dist/img/user8-128x128.jpg' ) }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE-master/dist/img/user3-128x128.jpg' ) }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>